web/router.ex
defmodule Portfolio.Router do
  use Portfolio.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Portfolio.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Portfolio do
    pipe_through :browser # Use the default browser stack

    get "/about", AboutController, :index
    get "/preferences", UserController, :preferences
    put "/preferences/:id", UserController, :update
    resources "/posts", PostController
    get "/", PostController, :index
  end

  scope "/auth", Portfolio do
    pipe_through :browser

    get "/new", UserAuthController, :sign_in
    get "/signout", UserAuthController, :sign_out
    get "/:provider", UserAuthController, :request
    get "/:provider/callback", UserAuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Portfolio do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Portfolio.LayoutView do
  use Portfolio.Web, :view

  
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Misch Portfolio</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation navbar-fixed-top" class="red">
          <div class="nav-wrapper container">
            <div class="left" style="height: 64px">
              <a href="/" style="text-decoration: none"> Discussions </a>
            </div>
            <ul class="right">
            <%= if @conn.assigns[:user] do %>
              <li>
                <%= link "Sign Out", to: user_auth_path(@conn, :sign_out) %>
              </li>
              <li>
                <%= link "Preferences", to: user_path(@conn, :preferences) %>
              </li>
            <% else %>
              <li>
                <%= link "Sign in with Github", to: user_auth_path(@conn, :request, "github") %>
              </li>
              <li>
                <%= link "Sign in with Twitter", to: user_auth_path(@conn, :request, "twitter") %>
              </li>

            <% end %>
              <li> <%= link "About", to: about_path(@conn, :index) %>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <% 
        info = get_flash(@conn, :info)
        error = get_flash(@conn, :error)
      %>
      <%= if info do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      
      <%= if error do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>